import { readFileSync, writeFileSync, existsSync, mkdirSync, chmodSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join } from "node:path";
import { loadConfig, fail, deferredGates } from "./lib.mjs";

const MARKER = "# generated by agent-pipeline/scripts/install-hooks.mjs";

/**
 * Each hook's commands, by configuration key.
 *
 * `pre-commit` guards what must never enter the history. `pre-push` guards
 * what must never reach the shared branch, plus the generated targets: it was
 * a generated target falling out of sync that motivated this script, nobody
 * having seen it go out in a merge.
 *
 * `build`, the full suite and `audit` are deliberately absent: they belong to
 * CI or to QA's closing battery, and a slow hook ends up bypassed.
 */
const HOOKS = {
  "pre-commit": { commands: ["lint", "secrets_scan"], generated: false },
  "pre-push": { commands: ["check", "lint"], generated: true },
};

/**
 * Generated-target checks added to `pre-push`.
 *
 * The map's own gate is not among them, and no longer runs here: it is a
 * closure gate. The map is stale on the branch until the orchestrator
 * regenerates it, so a hook checking it would refuse every push from the
 * first export added until the pull request — and a hook that refuses
 * legitimate work is a hook people learn to bypass.
 */
const GENERATED_CHECKS = [
  "node agent-pipeline/scripts/sync-briefs.mjs --check",
  "node agent-pipeline/scripts/apply-profile.mjs --check",
];

/**
 * Renders a hook's content from the profile commands.
 *
 * The hook knows no stack: it only calls the values `commands` carries, in
 * order, and stops at the first failure. Changing ecosystem changes only the
 * configuration.
 *
 * @param name - hook name
 * @param config - project configuration
 * @returns the hook's shell script
 */
function renderHook(name, config) {
  const spec = HOOKS[name];
  const lines = ["#!/bin/sh", MARKER, "# Do not edit by hand: re-run install-hooks.mjs.", "set -e", ""];

  const deferred = deferredGates(config);
  for (const key of spec.commands) {
    if (deferred.has(key)) continue;
    const command = config.commands?.[key];
    if (typeof command !== "string") fail(`commands.${key} missing: the ${name} hook cannot be rendered`);
    lines.push(`echo "[${name}] ${key}"`, command, "");
  }

  if (spec.generated) {
    for (const check of GENERATED_CHECKS) lines.push(`echo "[${name}] generated target"`, check, "");
  }

  return lines.join("\n");
}

/**
 * Returns the hooks directory, honouring `core.hooksPath`.
 *
 * A repository that redirected its hooks plus a script writing into
 * `.git/hooks` produce the worst case: files that are present and that
 * nothing executes.
 *
 * @returns the path of the hooks directory
 */
function hooksDir() {
  let configured = "";
  try {
    configured = execFileSync("git", ["config", "--get", "core.hooksPath"], { encoding: "utf8" }).trim();
  } catch {
    configured = "";
  }
  if (configured.length > 0) return configured;

  const gitDir = execFileSync("git", ["rev-parse", "--git-common-dir"], { encoding: "utf8" }).trim();
  return join(gitDir, "hooks");
}

/**
 * Installs the git hooks, or checks that they are installed and current.
 *
 * The pipeline had always claimed that `pre-push` refuses a generated target
 * that has fallen out of sync. Nothing installed it: the claim was true on
 * paper and false on disk, and that is how a stale brief got pushed and then
 * merged with nothing to report it. This script is what was missing behind
 * the sentence.
 *
 * An existing hook that does not carry this script's marker is never
 * overwritten without `--force`: it belongs to somebody else.
 *
 * Usage: node install-hooks.mjs [--check] [--force]
 */
function main() {
  const args = process.argv.slice(2);
  const checkMode = args.includes("--check");
  const force = args.includes("--force");
  const config = loadConfig();
  const dir = hooksDir();

  let drift = false;
  for (const name of Object.keys(HOOKS)) {
    const path = join(dir, name);
    const wanted = renderHook(name, config);
    const current = existsSync(path) ? readFileSync(path, "utf8") : null;

    if (checkMode) {
      if (current == null) {
        console.error(`absent : ${path}`);
        drift = true;
      } else if (current !== wanted) {
        console.error(`out of sync: ${path}`);
        drift = true;
      }
      continue;
    }

    if (current != null && !current.includes(MARKER) && !force) {
      fail(`${path} exists and was not generated by this script. Read it, then re-run with --force to overwrite.`);
    }

    mkdirSync(dir, { recursive: true });
    writeFileSync(path, wanted);
    chmodSync(path, 0o755);
    console.log(`written: ${path}`);
  }

  if (checkMode) {
    if (drift) {
      fail("Hooks missing or stale. Run install-hooks.mjs without --check.");
    }
    console.log("Hooks installed and up to date.");
  }
}

main();
