import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync } from "node:fs";
import { join, dirname, relative, sep } from "node:path";
import { loadConfig, fail } from "./lib.mjs";
import { DEFAULT_EXTENSIONS, walk, declarationsIn } from "./surface.mjs";

/**
 * Renders the map as a deterministic Markdown document.
 *
 * @param files - the files scanned, with their declarations
 * @param roots - the configured roots
 * @returns the complete document
 */
function render(files, roots) {
  const total = files.reduce((sum, file) => sum + file.declarations.length, 0);
  const silent = files.filter((file) => file.declarations.length === 0).length;
  const lines = [
    "# Project map",
    "",
    "GENERATED by `agent-pipeline/scripts/project-map.mjs`. Do not edit by hand: the `project_map`",
    "gate replays the generation and fails on any drift.",
    "",
    "This is the answer to \"does this already exist?\". The reuse note demanded of every creation is",
    "judged against it, and the `duplication` gate refuses what it did not stop.",
    "",
    "**How it is built, and what it misses.** This generator recognises declarations by **pattern**,",
    "it does not parse any language. A re-export through an index, a name assembled at runtime and a",
    "class member are invisible to it, and so is anything shaped differently from the idioms it knows.",
    "A profile that needs roles, routes and types points `commands.project_map` at a generator that",
    "really parses its language.",
    "",
    `Roots: ${roots.map((root) => `\`${root}\``).join(", ")}. ${files.length} files, ${total} declarations` +
      `${silent > 0 ? `, ${silent} file(s) with nothing recognised` : ""}.`,
    "",
  ];

  let directory = null;
  for (const file of files) {
    const parent = dirname(file.path);
    if (parent !== directory) {
      directory = parent;
      lines.push(`## ${parent}`, "");
    }
    lines.push(`### ${file.path}`, "");
    if (file.declarations.length === 0) {
      lines.push("- _no declaration recognised by pattern_", "");
      continue;
    }
    for (const entry of file.declarations) {
      lines.push(`- \`${entry.name}\` — ${entry.kind}${entry.doc ? ` — ${entry.doc}` : ""}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

/**
 * Generates the project map, or checks that the rendered one still matches.
 *
 * The failure this guards against is not a missing map, it is an EMPTY one. A
 * generator written for another stack walks a tree it does not recognise,
 * produces a near-empty document, and `--check` then compares empty with
 * empty and exits 0. The result is a green gate asserting nothing, worse than
 * no gate since checking stops. Hence the two refusals below: no file found,
 * and not a single declaration recognised.
 *
 * Usage: node project-map.mjs [--check]
 */
function main() {
  const checkMode = process.argv.includes("--check");
  const config = loadConfig();
  const settings = config.project_map ?? {};
  if (!Array.isArray(settings.roots) || settings.roots.length === 0) {
    fail("project_map.roots missing: name the directories to map. The framework does not guess them.");
  }
  const out = typeof settings.out === "string" ? settings.out : "docs/project-map.md";
  const extensions = Array.isArray(settings.extensions) ? settings.extensions : DEFAULT_EXTENSIONS;
  const skip = typeof settings.skip === "string" ? new RegExp(settings.skip) : null;

  const files = [];
  for (const root of settings.roots) {
    for (const path of walk(root, skip)) {
      if (!extensions.some((extension) => path.endsWith(extension))) continue;
      files.push({ path: relative(".", path).split(sep).join("/"), declarations: declarationsIn(readFileSync(path, "utf8")) });
    }
  }
  files.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));

  if (files.length === 0) {
    fail(
      `no file to map under ${settings.roots.join(", ")} with extensions ${extensions.join(", ")}. ` +
        "An empty map passes every check while answering nothing: set project_map.extensions to this " +
        "project's source files, or point commands.project_map at a generator that knows them.",
    );
  }

  const total = files.reduce((sum, file) => sum + file.declarations.length, 0);
  if (total === 0) {
    fail(
      `${files.length} file(s) scanned and not one declaration recognised. This generator matches shapes, ` +
        "not syntax, and evidently not this project's. A map that names nothing answers no question, and " +
        "map-coverage would still pass it. Point commands.project_map at a generator for your language.",
    );
  }

  const rendered = render(files, settings.roots);
  const silent = files.filter((file) => file.declarations.length === 0).length;

  if (checkMode) {
    let current = null;
    try {
      current = readFileSync(out, "utf8");
    } catch {
      fail(`map not found: ${out}. Run project-map.mjs without --check.`);
    }
    if (current !== rendered) fail(`${out} is stale: it no longer matches the code. Regenerate it.`);
    console.log(`${out} is current: ${files.length} file(s), ${total} declaration(s).`);
    return;
  }

  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, rendered);
  console.log(`written: ${out} (${files.length} file(s), ${total} declaration(s))`);
  if (silent > 0) {
    console.log(`  ${silent} file(s) with no recognised declaration — the map lists them and says so.`);
  }
}

if (process.argv[1]?.endsWith("project-map.mjs")) main();
