import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { loadConfig, loadRules, pathAllowed, isGenerated, fail } from "./lib.mjs";

/**
 * Confronts a handoff's declared files with the real git diff.
 *
 * Reports both directions: a file modified but undeclared, and a file
 * declared but never touched. Applies the role's file policy to the observed
 * paths, not to the declared ones.
 *
 * A generated path is refused outright for every role but the orchestrator.
 * The project map is a function of the whole source tree: an issue that
 * commits it commits a state including whatever a parallel agent had
 * half-written, and the reviewer then reads a diff its author cannot
 * account for. One writer regenerates it once the issue is closed.
 *
 * Usage: node verify-scope.mjs <handoff.json> <base-ref>
 */
function main() {
  const [handoffPath, baseRef] = process.argv.slice(2);
  if (!handoffPath || !baseRef) fail("usage : verify-scope.mjs <handoff.json> <base-ref>");
  const handoff = JSON.parse(readFileSync(handoffPath, "utf8"));
  const rules = loadRules();
  const config = loadConfig();
  const sha = handoff.evidence?.commit_sha;
  if (!sha) fail("the handoff carries no commit_sha, nothing to verify");

  let diff;
  try {
    diff = execFileSync("git", ["diff", "--name-only", `${baseRef}..${sha}`], { encoding: "utf8" });
  } catch (error) {
    fail(`git diff a echoue : ${error.message}`);
  }
  const changed = diff.split("\n").filter((line) => line.length > 0);
  const declared = new Set(handoff.evidence.files ?? []);
  const policy = rules.file_policy?.[handoff.agent];
  const errors = [];

  const generated = (file) => isGenerated(file, config);
  const writesGenerated = handoff.agent === "orchestrator";

  for (const file of changed) {
    if (generated(file)) {
      if (!writesGenerated) {
        errors.push(
          `generated file committed by ${handoff.agent}: ${file}. It is regenerated by the orchestrator ` +
            "once the issue closes, from a tree where no other agent is mid-write.",
        );
      }
      continue;
    }
    if (!declared.has(file)) errors.push(`modified but undeclared: ${file}`);
    if (!pathAllowed(file, policy)) errors.push(`hors role ${handoff.agent} : ${file}`);
  }
  for (const file of declared) {
    if (generated(file)) continue;
    if (!changed.includes(file)) errors.push(`declared but never touched: ${file}`);
  }

  if (errors.length > 0) {
    for (const error of errors) console.error(`scope : ${error}`);
    process.exit(1);
  }
  console.log(
    `scope verified: ${changed.length} file(s), ${baseRef}..${sha}, role ${handoff.agent}, ${new Date().toISOString()}`
  );
}

main();
